Repository LunarG/gfxreconstruct, pull requests merged in 2022-10, with the labels that each got.

#830 Toascii - Header Line with source, version, commit.
  framework/decode/vulkan_ascii_consumer_base.cpp
  framework/decode/vulkan_ascii_consumer_base.h
  tools/toascii/main.cpp
Labels: P1, toascii

#834 Renamed gfxrecon-toascii to gfxrecon-convert
  BUILD.md
  README.md
  tools/CMakeLists.txt
  tools/convert/CMakeLists.txt
  tools/convert/README.md
  tools/convert/main.cpp
Labels: P1, toascii

#836 Document gfxrecon-convert and JSON Lines Format
  USAGE_desktop.md
  tools/convert/README.md
Labels: P1, convert, 1.0 Release

#850 JSON String Escaping
  framework/decode/custom_vulkan_ascii_consumer.h
  framework/decode/custom_vulkan_struct_decoders_to_string.cpp
  framework/generated/generated_vulkan_struct_decoders_to_string.cpp
  framework/generated/generated_vulkan_struct_to_string.cpp
  framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py
  framework/generated/vulkan_generators/vulkan_struct_to_string_body_generator.py
  framework/util/custom_vulkan_to_string.cpp
  framework/util/test/main.cpp
  framework/util/to_string.h
Labels: P1, convert

#851 Convert - Changed Default Extension to jsonl
  USAGE_desktop.md
  tools/convert/README.md
  tools/convert/main.cpp
Labels: P1, convert

#803 Add VkImportMemoryHostPointerInfoEXT replaying support
  framework/decode/vulkan_replay_consumer_base.cpp
  framework/decode/vulkan_replay_consumer_base.h
  framework/util/page_guard_manager.cpp
  framework/util/platform.h
Labels: P1, 1.0 Release

#852 Add Convert to gfxrecon.py and Enable it in Build
  USAGE_desktop.md
  tools/CMakeLists.txt
  tools/gfxrecon/gfxrecon.py
Labels: P1, convert, 1.0 Release

#860 Changed JSON index From Just Functions to all Blocks.
  framework/decode/file_processor.cpp
  framework/decode/file_processor.h
  tools/convert/README.md
Labels: convert

#863 Trimming vkSetLocalDimmingAMD
  framework/encode/custom_vulkan_encoder_commands.h
  framework/encode/vulkan_capture_manager.cpp
  framework/encode/vulkan_capture_manager.h
  framework/encode/vulkan_handle_wrappers.h
  framework/encode/vulkan_state_tracker.cpp
  framework/encode/vulkan_state_tracker.h
  framework/encode/vulkan_state_writer.cpp
Labels: 1.0 Release

#855 Lazily resize tracked swapchain images vector
  framework/decode/vulkan_replay_consumer_base.cpp
  framework/encode/vulkan_state_tracker.cpp
  framework/encode/vulkan_state_tracker_initializers.h
  framework/encode/vulkan_state_writer.cpp
Labels: 1.0 Release
