Repository LunarG/gfxreconstruct, pull requests merged in 2023-12, with the labels that each got.

#1383 Removed Lambda Indirection For MetaCommand to JSON
  framework/decode/json_writer.h
  framework/decode/metadata_json_consumer.h
Labels: convert

#1384 Reordered Integer Compare Before String
  framework/decode/json_writer.cpp
Labels: convert

#1287 Added handling missing VK_EXT_swapchain_colorspace
  USAGE_android.md
  USAGE_desktop_Vulkan.md
  android/scripts/gfxrecon.py
  framework/decode/vulkan_feature_util.cpp
  framework/decode/vulkan_feature_util.h
  framework/decode/vulkan_replay_consumer_base.cpp
  framework/decode/vulkan_replay_options.h
  framework/generated/generate_vulkan.py
  framework/generated/generated_vulkan_constant_maps.h
  framework/generated/vulkan_generators/gencode.py
  framework/generated/vulkan_generators/vulkan_constant_maps_generator.py
  tools/replay/replay_settings.h
  tools/tool_settings.h
Labels: P1

#1265 Adding the capture options to annotation for display with info tool
  framework/encode/capture_manager.cpp
  framework/encode/capture_manager.h
  framework/format/format.h
  tools/info/main.cpp
Labels: P2
