Repository LunarG/gfxreconstruct, pull requests merged in 2023-04, with the labels that each got.

#1015 Clean up Android build instructions
  BUILD.md
  HOWTO_android.md
  USAGE_android.md
  USAGE_desktop_D3D12.md
  USAGE_desktop_Vulkan.md
Labels: documentation

#1084 Android docs: Fixed invalid TOC entries
  USAGE_android.md
Labels: documentation

#886 Flush After Presents
  framework/encode/capture_manager.cpp
Labels: capture

#1100 Added SplitString and RemoveWhitespace Functions
  framework/decode/dx12_ascii_consumer_base.h
  framework/encode/capture_settings.cpp
  framework/util/options.cpp
  framework/util/strings.cpp
  framework/util/strings.h
  framework/util/test/main.cpp
  tools/platform_debug_helper.cpp
  tools/tool_settings.h
Labels: enhancement, P1

#1104 Made Vulkan Replay Consumer Options Const
  framework/decode/vulkan_replay_consumer_base.h
Labels: enhancement, replay
