Repository LunarG/gfxreconstruct, pull requests merged in 2024-10, with the labels that each got.

#1785 Adjust output array sizes for D3D12 replay
  framework/decode/dx12_object_info.h
  framework/decode/dx12_replay_consumer_base.h
  framework/generated/dx12_generators/dx12_api_call_encoders_body_generator.py
  framework/generated/dx12_generators/dx12_base_generator.py
  framework/generated/dx12_generators/dx12_replay_consumer_body_generator.py
  framework/generated/dx12_generators/dx12_wrapper_body_generator.py
  framework/generated/generated_dx12_api_call_encoders.cpp
  framework/generated/generated_dx12_replay_consumer.cpp
  framework/generated/vulkan_generators/base_generator.py
Labels: P1, replay, d3d12

#1796 Remove duplicate third-party license text
  LICENSE_ThirdParty.txt
  external/README.md
Labels: documentation

#1677 Add print block info option on android
  USAGE_android.md
  tools/replay/android_main.cpp
Labels: P2, replay, vulkan

#1803 Also run ci_build on openxr-experimental
  .github/workflows/ci_build.yml
  android/layer/build.gradle
  android/tools/replay/build.gradle
  framework/format/platform_types.h
Labels: P1, openxr-experimental

#1566 Add transformer annotation
  framework/decode/file_transformer.cpp
  framework/decode/file_transformer.h
  framework/format/format.h
  tools/compress/compression_converter.cpp
  tools/optimize/dx12_optimize_util.cpp
  tools/optimize/main.cpp
Labels: P2

#1412 - Add VK_KHR_DISPLAY_EXTENSION_NAME return to GetWsiExtensionName
  tools/tool_settings.h
Labels: P2, replay, vulkan

#1758 Handle shader extraction and replacement for less common cases
  framework/decode/vulkan_replay_consumer_base.cpp
  framework/decode/vulkan_replay_consumer_base.h
  framework/decode/vulkan_replay_dump_resources.cpp
  tools/extract/main.cpp
Labels: P1

#1805 fix collision of kViewRelativeLocation
  framework/format/format.h
Labels: P1, capture, replay, openxr-experimental

#1680 dx12 option: GFXRECON_CAPTURE_DRAW_CALLS
  USAGE_desktop_D3D12.md
  framework/decode/dx12_browse_consumer.h
  framework/decode/dx12_dump_resources.cpp
  framework/decode/dx12_dump_resources.h
  framework/decode/dx12_object_info.h
  framework/decode/dx12_replay_consumer_base.cpp
  framework/decode/dx12_replay_consumer_base.h
  framework/decode/dx_replay_options.h
  framework/encode/api_capture_manager.h
  framework/encode/capture_manager.cpp
  framework/encode/capture_manager.h
  framework/encode/capture_settings.cpp
  framework/encode/capture_settings.h
  framework/encode/d3d12_capture_manager.cpp
  framework/encode/d3d12_capture_manager.h
  framework/encode/dx12_object_wrapper_info.h
  framework/encode/dx12_state_tracker.cpp
  framework/encode/dx12_state_writer.cpp
  framework/generated/dx12_generators/capture_overrides.json
  framework/generated/dx12_generators/dx12_wrapper_body_generator.py
  framework/generated/generated_dx12_wrappers.cpp
  framework/graphics/dx12_resource_data_util.cpp
  framework/graphics/dx12_resource_data_util.h
  framework/graphics/dx12_util.cpp
  framework/graphics/dx12_util.h
  framework/util/options.cpp
  framework/util/options.h
  tools/replay/desktop_main.cpp
  tools/tool_settings.h
Labels: P1, d3d12

#1795 Fix invalid usage by waiting on CommandBuffer fence before resetting CommandBuffer
  framework/decode/vulkan_object_info.h
  framework/decode/vulkan_replay_consumer_base.cpp
  framework/decode/vulkan_virtual_swapchain.cpp
  framework/decode/vulkan_virtual_swapchain.h
Labels: P2, replay, vulkan

#1799 Vulkan dump resources convert with blit
  USAGE_android.md
  USAGE_desktop_Vulkan.md
  android/scripts/gfxrecon.py
  framework/decode/vulkan_replay_dump_resources_common.cpp
  framework/decode/vulkan_replay_dump_resources_common.h
  framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.cpp
  framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.h
  framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
  framework/decode/vulkan_replay_dump_resources_draw_calls.h
  framework/decode/vulkan_replay_dump_resources_json.cpp
  framework/decode/vulkan_replay_options.h
  framework/graphics/vulkan_resources_util.cpp
  framework/graphics/vulkan_resources_util.h
  framework/util/image_writer.cpp
  framework/util/image_writer.h
  tools/replay/replay_settings.h
  tools/tool_settings.h
Labels: P1, vulkan

#1815 Add acceleration structure meta-commands
  android/framework/encode/CMakeLists.txt
  framework/decode/api_decoder.h
  framework/decode/file_processor.cpp
  framework/decode/metadata_consumer_base.h
  framework/decode/vulkan_decoder_base.cpp
  framework/decode/vulkan_decoder_base.h
  framework/decode/vulkan_replay_consumer_base.cpp
  framework/decode/vulkan_replay_consumer_base.h
  framework/encode/CMakeLists.txt
  framework/encode/vulkan_capture_manager.cpp
  framework/encode/vulkan_device_address_tracker.cpp
  framework/encode/vulkan_device_address_tracker.h
  framework/encode/vulkan_handle_wrapper_util.h
  framework/encode/vulkan_handle_wrappers.h
  framework/encode/vulkan_state_tracker.cpp
  framework/encode/vulkan_state_tracker.h
  framework/encode/vulkan_state_writer.cpp
  framework/encode/vulkan_state_writer.h
  framework/format/format.h
Labels: P1

#1835 Fix crash in CreateCommandList1 when trimming
  framework/encode/dx12_state_tracker.cpp
Labels: capture, trimming, d3d12
